### ISSUE TITLE
directories should be created with recursive by default

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-v05-compat#28]
current: error when creating directories with recursive

expected: can create directories with recursive by default

workaround: create a directory by directory

example config:

```yaml
nodes:
  - _id: "0"
    provisioners:
      - _id: 'v05-compat-chef'
        json:
          teracy-dev:
            directories:
              - _id: "iorad-common-certs-dir"
                path: /etc/nginx/certs
                owner: vagrant
                group: vagrant
                mode: '0755'
                action: create
                recursive: true # TODO: support this
```
