### ISSUE TITLE
docker-compose was not re-installed when its version config changed

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-v05-compat#40]
- Given:
  + use teracy-dev v0.6.0-a8
  + create the `workspace/teracy-dev-entry/config_default.yaml` file with the following content, notice `docker-compose.version: '1.25.3'`:

  ```yaml
  teracy-dev:

    extensions:

      - _id: "entry-v05-compat"
        path:
          extension: teracy-dev-v05-compat
        location:
          git:
            remote:
              origin: https://github.com/teracyhq-incubator/teracy-dev-v05-compat.git
            branch: develop
        require_version: ">= 0.5.0-SNAPSHOT"
        enabled: true

      - _id: "entry-essential"
        path:
          extension: teracy-dev-essential
        location:
          git:
            remote:
              origin: https://github.com/teracyhq-incubator/teracy-dev-essential.git
            branch: v0.7.0
        require_version: ">= 0.7.0"
        enabled: true


      - _id: "kernel-core"
        location: # auto download the extension into the lookup_path
          git:
            remote:
              origin: https://github.com/teracyhq-incubator/teracy-dev-core.git
            branch: v0.4.0
        require_version: ">= 0.4.0"
        enabled: true


  nodes:
    - _id: "0"
      provisioners:
        - _id: "v05-compat-chef"
          json:
            docker_compose:
              version: '1.25.3' # more: https://github.com/docker/compose/releases/
  ```

- When `$ vagrant up` finished
- Then `$ vagrant ssh -c "docker-compose version"` should output:

  ```bash
  docker-compose version 1.25.3, build d4d1b42b
  ```
- Given updating the `docker-compose.version` to `1.25.4`
- When `$ vagrant reload --provision` finished
- Then `$ vagrant ssh -c "docker-compose version"` should output:

  ```bash
  docker-compose version 1.25.4, build xxxxxx
  ```

- But actually:

```
bash: docker-compose: command not found
```

- Workaround solution: `$ vagrant reload --provision` one more time
